name: homework_movie_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  firebase_auth: ^3.3.15
  firebase_core: ^1.14.1
  flutter:
    sdk: flutter
  flutter_redux: ^0.9.0
  http: ^0.13.4
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13


  cupertino_icons: ^1.0.2


dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.6


  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:


  uses-material-design: true

